### ISSUE TITLE
 Bug while using onDuplicateKeyUpdate in mysql.

### ISSUE THREAD

**Issue by attolife** [komapper/komapper#1001]
### Describe the bug

QueryDsl.insert(meta).onDuplicateKeyUpdate(meta.meno).single(error)

### Expected behavior
already has meno key but not update only insert..

### Steps to reproduce the problem

@KomapperTable("error")
@KomapperEntityDef(entity = Error::class, aliases = ["error"])
data class ErrorEntity(
    @KomapperId @KomapperAutoIncrement var meno:Nothing,
    @KomapperColumn(name="os_version")var osVersion:Nothing,
    @KomapperColumn(name="app_version")var appVersion:Nothing,
    @KomapperCreatedAt var regdt:Nothing
)

so checking dubug query

insert into error(os_version, app_version, regdt) values('1111', '2222', '2023-01-01 11:11:11')
on duplicate key update os_version='1111'

but Actual behavior is

insert into error(meno, os_version, app_version) values('', '', '')
on duplicate key update ....

so.. onDuplicateKeyUpdate is method use auto_increment column need~~

- A complete set of DDL statements can help re-create the setup you're having

### Versions

- Komapper: 1.10.0
- Kotlin:
- JVM:
- JDBC Driver or R2DBC Driver: r2dbc
- Database: mysql
- OS: osx

**Comment by nakamura-to** [comment]
If you use the auto_increment column, the primary key is never duplicated. 
Therefore, an INSERT is always performed.

In that case you do not need to use onDuplicateKeyUpdate.

**Comment by attolife** [comment]
yes insert into no problem..
but i want update same primary key

**Comment by nakamura-to** [comment]
If you know the primary key in advance simply perform an update.
https://www.komapper.org/docs/reference/query/querydsl/update/
