### ISSUE TITLE
Entity inheritance

### ISSUE THREAD

**Issue by d-wire** [komapper/komapper#1007]
### Use case
This may already exist and I just couldn't find it in the docs, but we would like to have a single base entity class for all of our entities to inherit from for consistency across shared fields, for example: id, created_at, and updated_at.

### Describe the solution you'd like
Trying to do something like this:
```
@KomapperEntity
open class BaseEntity(
    @KomapperId
    @KomapperAutoIncrement
    var id: Long = 0,

    @KomapperCreatedAt
    var createdAt: Instant? = null,

    @KomapperUpdatedAt
    var updatedAt: Instant? = null,
)
```

And then subsequent entities can do
```
@KomapperEntity
data class ANewEntity(
    @KomapperColumn("tx_id")
    var txId: String,

    @KomapperColumn("account_id")
    var accountId: String,

    @KomapperColumn("amount_usd")
    var amountUsd: BigDecimal,
) : BaseEntity()
```
but it seems to want a specific id field on the new entity itself. Jakarta had a @MappedSuperClass which was basically for exactly this use case, but that doesn't work super easily with R2DBC, so something like that would be super nice.

### Versions
Using:
- Komapper: 1.11.0
- Kotlin: 1.7.22
- JVM: 17
- R2DBC Driver: latest
- Database: Postgres

**Comment by nakamura-to** [comment]
Komapper does not support entity inheritance.
Komapper is committed to immutability, so we do not plan to support features like inheritance that prevent immutability.
