### ISSUE TITLE
Liquibase integration

### ISSUE THREAD

**Issue by d-wire** [komapper/komapper#1014]
### Use case
Can this be integrated to use with Liquibase? We're using Liquibase to manage our migrations and I was wondering if the code generation section of Komapper can be integrated to work with Liquibase. Or if the code generation can output raw SQL that we can then import into Liquibase.

### Describe the solution you'd like
Easy clean integration with Liquibase.

**Comment by nakamura-to** [comment]
I am not familiar with Liquibase, but I believe it can be used with Komapper. 

Manage your database schema with Liquibase and generate Kotlin code from the database using the [Gradle plugin](https://www.komapper.org/docs/reference/gradle-plugin/) provided by Komapper.

Let me know if you have any problems using them together.
