### ISSUE TITLE
KSP ignores `@KomapperTable` annotation and generates `Meta.entityClassName`

### ISSUE THREAD

**Issue by yu-ishicawa** [komapper/komapper#1015]
### Describe the bug

Even when entity classes are prefixed or suffixed, the Meta class generated by KSP are based on the Entity class name.

For example, for the following entity class
```
@KomapperEntity
@KomapperTable("address")
data class AddressEntity(
  ...
)
```

`Meta.addressEntity` is generated. Is this the intended behavior?

### Expected behavior

I expect it to be generated based on the table name specified in `@KomapperTable` annotation. In the above case, `Meta.address`

### Actual behavior

As noted above.

### Versions

- Komapper: 1.11.0

**Comment by nakamura-to** [comment]
Yes, that is the intended behavior.
QueryDsl of Komapper is DSL for entities, not tables.

**Comment by yu-ishicawa** [comment]
@nakamura-to 
Thank you for your response.

I see, then I may have made an unnecessary modification in my previous PR.
https://github.com/komapper/komapper/pull/1012/files#diff-a69ad9ba1d8b117aa7c71558a3c932cb0c1463730c05c1864d4e76bb9eef9b99R122-R126

When the code generator outputs aliases, the prefix and suffix are ignored.
If `singularize` is set to `true` and `suffix` is set to `Entity`, the following code will be output.

```
@KomapperEntityDef(AddressEntity::class, ["addresses"])
@KomapperTable("ADDRESSES")
data class AddressEntityDef (
    ...
)
```
And KSP generates only `Meta.addresses`.

Should I revert this one so that it does not output aliases?

Apart from that, are there any plans to add an option to allow KSP to output metamodel names based on table names?

**Comment by nakamura-to** [comment]
> Should I revert this one so that it does not output aliases?

No, your PR is acceptable. However, you may revert if you wish.
The suffix only applies if the name is auto-resolved.

> are there any plans to add an option to allow KSP to output Meta.tableName based on table names?

I have no plan.

I have a question. When you resolve metamodel names based on table names, do you want to resolve metamodel property names based on column names?

**Comment by yu-ishicawa** [comment]
> I have a question. When you resolve metamodel names based on table names, do you want to resolve metamodel property names based on column names?

Hmmm, I hadn't thought that far ahead. In my case, I want the entity classes to be automatically generated from the database definition, so the column names, entity class property names, and metamodel property names will all be the same.

While thinking about it, I came up with a good idea.
have been using the value of `singularize` to output aliases in Gradle plugin, but I want to modify it to use another option called `useAliasAsTableName` instead.
