### ISSUE TITLE
Update Quarkus Extension to v3

### ISSUE THREAD

**Issue by raharrison** [komapper/komapper#1039]
### Use case

Currently the komapper-quarkus-jdbc/r2dbc extensions are tied to Quarkus version 2.16.9.Final. The latest Quarkus is 3.2.3.Final.

### Describe the solution you'd like

Update the extension to use the latest major Quarkus versions.

I think for the most part things should work in place. The main difference from Quarkus 2->3 is the package switch from `javax` to `jakarta`, but that should just be a direct replacement.

### Versions

- Komapper: 1.12.0
- Kotlin: 1.9.0
- JVM: N/A
- JDBC Driver or R2DBC Driver: Both
- Database: N/A
- OS: N/A

**Comment by nakamura-to** [comment]
Thanks for pointing that out.

**Comment by nakamura-to** [comment]
Try Komapper v1.12.1.
https://github.com/komapper/komapper/releases/tag/v1.12.1
