### ISSUE TITLE
Error when associating object from another package

### ISSUE THREAD

**Issue by jvgelder** [komapper/komapper#1091]
### Describe the bug

When a model is in a different package and try to create a relation with `KomapperOneToMany()` for example you get the following error : ` The targetEntity must be annotated with either @KomapperEntity or @KomapperEntityDef.`

### Expected behavior

When the target is properly annotated it should be properly resolved even if its is in a different package.

### Actual behavior

` The targetEntity must be annotated with either @KomapperEntity or @KomapperEntityDef.`

### Steps to reproduce the problem

```kotlin
package org.test.one

@KomapperEntity
data class MyTestModel(
   val id : Long;
)
```
Different package:

```kotlin
package org.test.two

import org.test.one.MyTestModel

@KomapperExperimentalAssociation
@KomapperOneToMany(MyTestModel::class, "mymodel")
@KomapperEntity
data class AnotherModel(
   val id : Long,
   val myModelId : Long
)
```
### Versions

- Komapper: 1.10.0
- Kotlin: 1.8
- JVM: 17
- JDBC Driver or R2DBC Driver: R2DBC
- Database: H2 / postgress
- OS:

**Comment by nakamura-to** [comment]
Thanks for your report.
I will fix it.
