### ISSUE TITLE
support INSTR

### ISSUE THREAD

**Issue by rwsbillyang** [komapper/komapper#1094]
Does komapper support [INSTR](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_instr)?
Not found related doc in https://www.komapper.org/docs/reference/.

 A use case in mysql8:
```SQL
select * from t_constant where id in (4,5,6,22,7)  ORDER BY INSTR(',4,5,6,22,7,', CONCAT(',', id, ','));
```
order by id  list sequence for inList query.

**Comment by nakamura-to** [comment]
We will support the locate function in #1095.
The instr function is the same as the two-argument form of locate function.

See https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_locate
