### ISSUE TITLE
Support Postgres Geo types

### ISSUE THREAD

**Issue by jvgelder** [komapper/komapper#1105]
### Use case

Would like to be able to query by or at least return / send `Geometry` and `Polygon` types that already exist in: 

R2dbc: https://github.com/pgjdbc/r2dbc-postgresql/blob/main/src/main/java/io/r2dbc/postgresql/codec/PostgisGeometryCodec.java

### Describe the solution you'd like

An implementation or some pointers to what I should implement.
I think the hardest part is being actually be able to query using stuff like:

```sql
select * from MyTable  where
ST_DWithin(geo_fence, ST_SetSRID(ST_POINT( 4.1234, 51.1223),4326), 300.0)
```
But I guess we can work around it by creating the query from a string?

But as mentioned above I would already be happy if I can define a`Geometry` / `Polygon` on my model:

```kotlin
data class mymodel {
 val polygon : io.r2dbc.postgresql.codec.Polygon
 val geometry : io.r2dbc.postgresql.codec.PostgisGeometryCodec
}
```

### Versions

- Komapper:  
- Kotlin: 1.7
- JVM: 17
- JDBC Driver or R2DBC Driver: R2DBC
- Database: Postgres
- OS:

**Comment by nakamura-to** [comment]
You should use the data type `org.locationtech.jts.geom.Geometry` instead of `PostgisGeometryCodec`.

So try the following code:

```kotlin
package example.basic.r2dbc

import io.r2dbc.spi.Row
import io.r2dbc.spi.Statement
import org.komapper.r2dbc.spi.R2dbcUserDefinedDataType
import org.locationtech.jts.geom.Geometry
import kotlin.reflect.KClass

class GeometryType: R2dbcUserDefinedDataType<Geometry> {
    override val name: String = "geometry"
    override val klass: KClass<Geometry> = Geometry::class
    override val r2dbcType: Class<Geometry> = Geometry::class.javaObjectType

    override fun getValue(row: Row, index: Int): Geometry? {
        return row.get(index, r2dbcType)
    }

    override fun getValue(row: Row, columnLabel: String): Geometry? {
        return row.get(columnLabel, r2dbcType)
    }

    override fun toString(value: Geometry): String {
        return value.toString()
    }

    override fun setValue(statement: Statement, name: String, value: Geometry) {
        statement.bind(name, value)
    }

    override fun setValue(statement: Statement, index: Int, value: Geometry) {
        statement.bind(index, value)
    }
}
```

You need to include the class name mentioned above into the `META-INF/services/org.komapper.r2dbc.spi.R2dbcUserDefinedDataType` file.

**Comment by jvgelder** [comment]
Error: `The dataType is not found for the type "org.example.database.customtypes.GeometryType"`

I cannot seem to generate the required files. Should META-INF be in the root of the jar ? 

My layout is as follows:

```
└── META-INF
    └── org.komapper.r2dbc.spi.R2dbcUserDefinedDataType
```

Contents of ` org.komapper.r2dbc.spi.R2dbcUserDefinedDataType`:
```
org.example.database.customtypes.GeometryType
```


We use bazel to build everything so It could be related to : https://github.com/bazelbuild/rules_kotlin/pull/997/files

**Comment by nakamura-to** [comment]
> Should META-INF be in the root of the jar ?

Yes.

I don't know about bazel, but if you're using Gradle, I believe the layout you've mentioned should work without any issues as long as it's located under the `src/main/resources` directory.

**Comment by nakamura-to** [comment]
Supported in version 1.15.0.
See https://www.komapper.org/docs/reference/dialect/#postgresql---r2dbc
