### ISSUE TITLE
@KomapperSequence behavior for multiple clients

### ISSUE THREAD

**Issue by ivsokol-ht** [komapper/komapper#1138]
### Describe the bug

I have Komapper DAO defined in this way

`
@KomapperEntity
@KomapperTable(name = "MY_TABLE")
data class TableDAO(
    @KomapperId
    @KomapperColumn(name = "PK_ID")
    @KomapperSequence(name = "MY_TABLE_SEQ")
    override val id: Long = 0,
... other fields removed for brevity
`

Beside my client on that particular table, there are also other clients. All clients are inserting new rows based on sequence.
I am inserting it like this 

`val query = QueryDsl.insert(myTable).single(row)
                db.runQuery(query)
`

In some cases (when other clients insert their rows) I receive 'unique constraint violated' error from DB. I see that komapper tried to insert last value that was successful + 1, even though DB sequence already went on some other value.

Is there some sort of cache on @KomapperSequence, and if there is, can it be turned off? I want to force komapper to always call next value from DB, and not from internally calculated value

### Expected behavior

@KomapperSequence will be in sync with DB sequence

### Actual behavior

@KomapperSequence is not in sync with DB sequence

### Steps to reproduce the problem

I am just trying to describe steps, later on I will try to make a dummy project that reproduces this behaviour

- create table with PK
- create sequence 
- insert row from Kommaper
- manually insert rows using sequence (so that DB sequence goes up)
- try again insert row from Komapper

### Versions

- Komapper: 1.8.0
- Kotlin: 1.8.10
- JVM: 17.0.6
- JDBC Driver or R2DBC Driver: JDBC - com.oracle.database.jdbc:ojdbc11:21.9.0.0
- Database: Oracle 12.1.0.2.0
- OS: Win 11

**Comment by ivsokol-ht** [comment]
Hi,
just additional question related to optimization and potential new feature:

Is it possible to use sequence annotation (perhaps in combination with auto increment annotation) to invoke nextval in insert statement? That would minimize database roundtrips and use database native capabilities

Oracle and Postgres supports this:

- https://www.tutorialsteacher.com/postgresql/sequence
- https://livesql.oracle.com/apex/livesql/file/content_GL1PAE2CYMKDK32A42NZIGJVR.html

Thank you.

**Comment by nakamura-to** [comment]
Unfortunately, that feature is not supported at the moment.
We would like to consider supporting it in the future.
Thank you for informing me about the feature.

**Comment by nakamura-to** [comment]
However, for that use case, it might be better to use an identity instead of a sequence. 
The following DDL works on Oracle Database.

```sql
create table my_table(id integer generated always as identity primary key, "value" varchar2(10));
```

In Komapper, the [@KomapperAutoIncrement](https://www.komapper.org/docs/reference/entity-class/#komapperautoincrement) annotation is used to support identity.

**Comment by ivsokol-ht** [comment]
Thanks for info. I am already using KomapperAutoIncrement annotation on other tables (those where "before insert" trigger generates an id), but on this particular table I must use sequence (I am not table owner)
