### ISSUE TITLE
Bug: H2 maps decimal to bigint

### ISSUE THREAD

**Issue by jvgelder** [komapper/komapper#1190]
### Describe the bug

H2 is mapping BigDecimals to but should map to numeric as according to the dialect docs? 
See: 

https://github.com/komapper/komapper/blob/3c69412c0bdbbc4e3ae3a2c5400cd61b2a5875c4/komapper-dialect-h2-jdbc/src/main/kotlin/org/komapper/dialect/h2/jdbc/H2JdbcDataTypeProvider.kt#L40

https://github.com/komapper/komapper/blob/3c69412c0bdbbc4e3ae3a2c5400cd61b2a5875c4/komapper-dialect-h2-r2dbc/src/main/kotlin/org/komapper/dialect/h2/r2dbc/H2R2dbcDataTypeProvider.kt#L34

### Expected behavior

"bigint" should be "numeric"

### Actual behavior

H2 returns a big int if the type is defined as `java.math.BigDecimal`

### Versions

- Komapper: 1.16
- Kotlin:
- JVM:
- JDBC Driver or R2DBC Driver:
- Database:
- OS:

**Comment by nakamura-to** [comment]
Thanks for your report.
