### ISSUE TITLE
[Q] What are the differences to kotlin exposed project

### ISSUE THREAD

**Issue by qoomon** [komapper/komapper#1209]
Hi there, thx for this amazing lib.
I'd like to understand the main differences between komapper and (exposed)[https://github.com/JetBrains/Exposed], maybe you can list som aspects?

**Comment by nakamura-to** [comment]
Hi, thank you for asking.

For example, the features of Komapper that are not available in Exposed are as follows:

- Supports R2DBC
- Generates code at compile time, allowing for early error detection and superior performance
- By default, it does not use reflection, making it easier to convert to native images
- Supports [Embedded Value](https://www.martinfowler.com/eaaCatalog/embeddedValue.html)
- Supports Kotlin value classes
- Supports optimistic locking
- Supports pessimistic locking
- Supports [SQL templates](https://www.komapper.org/docs/reference/query/querydsl/template/#sql-template)
- Supports various queries
  - CTEs
  - WINDOW functions
  - RETURNING clause

**Comment by qoomon** [comment]
Thanks a lot, I was look for exactly this kind of list.
