### ISSUE TITLE
Experimental Association API - Make Order Preservation part of API

### ISSUE THREAD

**Issue by austinarbor-wk** [komapper/komapper#1256]
Is there a reason the association api returns sets instead of lists? If I have sorting on the results, the _public api_ does not guarantee that the order is maintained.

After digging through the code in the code, the underlying set is created with `mutableSetOf()`, which in turn uses a `LinkedHashSet`. So, in practice order _should_ be preserved, but this order is not guaranteed anywhere by the API and that assumption could change at any moment.

Can we make this guarantee part of the public api?

**Comment by nakamura-to** [comment]
Thank you for asking the question.

> Is there a reason the association api returns sets instead of lists? 

Yes, returning sets indicates that the entities are not duplicated.

> Can we make this guarantee part of the public api?

Yes, we guarantee to preserve the order. We would like to document this in the API documentation in the next release.

**Comment by austinarbor-wk** [comment]
This could actually be condensed into a single class
```kotlin
@KomapperEntity
@KomapperOneToMany(targetEntity = Child::class, navigator = "children")
@KomapperAggregateRoot(navigator = "parents")
data class Parent(
  @KomapperId @AutoIncrement
  val id: Long,
  @KomapperIgnore @JsonIgnore private val store: EntityStore? = null,
) {
  @get:JsonIgnoreProperties("parent")
  val children by lazy {
   store?.oneToManyById(Meta.parent, Meta.child)?.get(id)?.map { it.copy(store = store) }
  }
}

@KomapperEntity
@KomapperManyToOne(Parent::class, navigator = "parent")
data class Child(
 @KomapperId @AutoIncrement
  val id: Long,
  val parentId: Long,
 @KomapperIgnore @JsonIgnore private val store: EntityStore? = null,
) {
  val parent by lazy {
    store?.manyToOneById(Meta.child, Meta.parent)?.get(id)?.copy(store = store)
  }
}

```

**Comment by nakamura-to** [comment]
> Is there any plan to provide ORM capabilities out of the box for the association api?

We do not have such a plan.
Thank you for the idea.
