### ISSUE TITLE
Entity with property named "java" breaks code generation

### ISSUE THREAD

**Issue by austinarbor** [komapper/komapper#1274]
### Describe the bug
If you have an entity with a property named "java", entity generation has problems

### Steps to reproduce the problem

```kotlin
@KomapperEntity
data class MyModel(
  @KomapperId val id: Long? = null,
  val someField: String,
  val java: Boolean,
  val someTime: OffsetDateTime
)
```

When KSP runs on that entity, you get the error
`_MyModel.kt:18:199 Unresolved reference: time`

### Versions

- Komapper: 1.18.0
- Kotlin: 1.9.24
- JVM: 21
- JDBC Driver or R2DBC Driver: Postgresql

**Comment by nakamura-to** [comment]
Thank you for the report. I will look into it.
