### ISSUE TITLE
K2 - Enum EnumType.Property

### ISSUE THREAD

**Issue by austinarbor** [komapper/komapper#1275]
### Describe the bug
Hello, I know you don't officially support Kotlin 2 yet, but I just wanted to let you know I did find an issue when testing it out

Given the entity
```kotlin
@KomapperEntity
data class MyModel(
  @KomapperId val id: Long? = null,
  @KomapperEnum(EnumType.PROPERTY, hint = "value") val myEnum: MyEnum,
)

enum class MyEnum(val value: Int) {
  SOMETHING(10)
}
```

There are no errors produced during code generation, however, during insert statements it ignores the `EnumType.PROPERTY` and `hint` values and tries to insert a string value for the enum instead.

This works fine on Kotlin 1.9.24 / KSP 1.9.24-1.0.20 but does not on Kotlin 2.0.0 / KSP 2.0.0-1.0.21 (with `ksp.useKSP2=true` set in gradle.properties)

### Versions

- Komapper: 1.8.10
- Kotlin: 2.0.0
- KSP: 2.0.0-1.0.21
- JVM: 21
- JDBC Driver or R2DBC Driver: Postgresql

**Comment by nakamura-to** [comment]
Thank you for letting me know. It looks like a bug in KSP 2. I will investigate and report it to the KSP team.

**Comment by nakamura-to** [comment]
I reported it to the KSP team.
https://github.com/google/ksp/issues/1928
