### ISSUE TITLE
Support subquery for greater, eq, less etc

### ISSUE THREAD

**Issue by jvgelder** [komapper/komapper#1293]
### Use case

To save db round trips I  would like  to be able to do queries like:

```sql
select * from MyTable where MyTable.myvar > (select distinct MyTable.myvar from  MyTable.id eq 'myid')
```
or 
```sql
select * from MyTable where MyTable.myvar between (select distinct MyTable.myvar from  MyTable.id eq 'myid') and  (select distinct MyTable.myvar from  MyTable.id eq 'anotherId') 
```

Sub-queries could also query other tables of course.

### Describe the solution you'd like

Make it possible to accept subqueries for:
- [x] eq  
- [x] notEq
- [x] less
- [x] lessEq
- [x] greater
- [x] greaterEq
- [ ] between

Maybe even for all others too ?

### Versions

- Komapper:
- Kotlin:
- JVM:
- JDBC Driver or R2DBC Driver:
- Database:
- OS:

**Comment by nakamura-to** [comment]
You can specify a scalar subquery as an operand for greater, eq, and less. In other words, use the max function to return a scalar value from the subquery.

```kotlin
val d = Meta.department
val e = Meta.employee

val subquery = QueryDsl.from(d).where {
    d.departmentName eq "SALES"
}.select(max(d.departmentId))

val query = QueryDsl.from(e).where {
    e.departmentId greater subquery
}.select(e.employeeName)

val list = db.runQuery(query)
```

The above query generates the following SQL.

```sql
select 
  t0_.employee_name 
from 
  employee as t0_ 
where 
  t0_.department_id > 
  (
    select 
      max(t1_.department_id) 
    from 
      department as t1_ 
    where 
      t1_.department_name = 'SALES'
  )
```

However, specifying a scalar subquery for the between operator is not supported.
