### ISSUE TITLE
Support of explicit API KSP2

### ISSUE THREAD

**Issue by Distractic** [komapper/komapper#1296]
### Describe the bug

The bug fixed in #835 is back again using KSP2

### Versions

- Komapper: 1.18.1
- Kotlin: 2.0.0
- JVM: 17
- JDBC Driver or R2DBC Driver: R2DBC
- Database: PostgreSQL
- OS: All

**Comment by nakamura-to** [comment]
Thank you for your feedback.
I have confirmed the issue.

I am considering ways to suppress the explicit API related errors as before, but since Kotlin 2.0.0, a warning message is output when using this method.

I am currently inquiring about this.
https://youtrack.jetbrains.com/issue/KT-69337
