### ISSUE TITLE
Better Support for Generic Types

### ISSUE THREAD

**Issue by austinarbor** [komapper/komapper#1301]
### Use case

Do you think it would be possible to add better support for generic types? With the use of jsonb and jsonb[], I wish it was easier to just use `Map<String,Any>` or `List<Map<String,Any>>` (or something similar) as my type without having to write wrapper types.

### Describe the solution you'd like
At least for all my types, anything that is a jsonb or jsonb array column is going to be converted by Jackson, so I'm really just looking for a simplified way to have columns like the below example, without having to create redundant wrapper types like `MapStringAnyType`. IMO that makes the api clunkier and I then also have to unnecessarily deal with the json serialization and deserialization.

```kotlin
data class MyEntity(
 @KomapperId val id: Long = 0,
 val someJsonData: Map<String, Any>?, 
 val someJsonArray: List<Map<String,Any>>?,
)
```
In the current state I need to define three classes to get this to work (per custom type) - i would need a 4th class if I also wanted to support json deserialization to this custom type

```kotlin
@JsonSerialize(using = Ser::class) data class MapStringAny(val map: Map<String, Any>)

class Ser : StdSerializer<MapStringAny>(MapStringAny::class.java) {
  override fun serialize(
      value: MapStringAny?,
      gen: JsonGenerator,
      provider: SerializerProvider,
  ) {
    if (value == null) {
      gen.writeNull()
    } else {
      gen.writeObject(value.map)
    }
  }
}

class JsonbMapStringAny : JdbcUserDefinedDataType<MapStringAny> {
  override val name: String = "jsonb"
  override val jdbcType = JDBCType.JAVA_OBJECT
  override val klass = MapStringAny::class
  private val mapper = jacksonMapperBuilder().build()

  override fun getValue(
      rs: ResultSet,
      index: Int,
  ): MapStringAny {
    val obj = rs.getString(index) ?: return MapStringAny(emptyMap())
    val v = mapper.readValue<Map<String, Any>>(obj)
    return MapStringAny(v)
  }

  override fun getValue(
      rs: ResultSet,
      label: String,
  ): MapStringAny {
    val v = mapper.readValue<Map<String, Any>>(rs.getString(label))
    return MapStringAny(v)
  }

  override fun setValue(
      ps: PreparedStatement,
      index: Int,
      value: MapStringAny,
  ) {
    ps.setString(index, mapper.writeValueAsString(value.map))
  }

  override fun toString(value: MapStringAny): String {
    return value.map.toString()
  }
}

```

### Versions

- Komapper: 1.18.1
- Kotlin: 2.0.0
- JVM: 21
- JDBC Driver or R2DBC Driver: Postgres

**Comment by nakamura-to** [comment]
Thank you for sharing your thoughts.
Unfortunately, we are unable to support generic types.
This is because it is impossible to uniquely identify the Komapper data type from generic types at runtime.

**Comment by austinarbor** [comment]
What do you mean by Komapper data type? Could that information be provided by annotation?

**Comment by austinarbor** [comment]
And something like this would never work?
```kotlin
class MapType: JdbcUserDefinedDataType<Map<String,Any>> {
  override val name: String = "jsonb"
  override val jdbcType = JDBCType.JAVA_OBJECT
  override val klass = Map::class as KClass<Map<String, Any>>
  private val mapper = jacksonObjectMapper()

  override fun getValue(rs: ResultSet, index: Int): Map<String,Any> {
    val s = rs.getString(index) ?: return emptyMap()
    return JsonMapperFactory.DEFAULT_MAPPER.readValue(s)
  }

  override fun getValue(rs: ResultSet, columnLabel: String): Map<String,Any> {
    val index = rs.findColumn(columnLabel)
    return getValue(rs, index)
  }

  override fun setValue(ps: PreparedStatement, index: Int, value: Map<String,Any>) {
    ps.setString(index, mapper.writeValueAsString(value))
  }

  override fun toString(value: Map<String,Any>): String {
    return value.toString()
  }
}
```

**Comment by nakamura-to** [comment]
That class will not work as intended. 
At runtime, `Map::class as KClass<Map<String, Any>>` does not retain the generic type information.

You can try it with a simple piece of code:
```kotlin
fun main() {
    val k1 = Map::class as KClass<Map<String, Any>>
    val k2 = Map::class as KClass<Map<Int, Any>>
    println(k1 == k2) // true
}
```

**Comment by austinarbor** [comment]
Using `KType` instead of `KClass` should work, but looks like that would be a pretty massive change to the code

**Comment by nakamura-to** [comment]
I wasn't aware that `KType` holds the type. Thank you for letting me know.
While I can't say for certain when, I will consider supporting generics using KType in the future.

**Comment by nakamura-to** [comment]
I have created the pull request #1303 to resolve this issue. 
If possible, could you please provide your comments?

We are considering adding this in the next major version.

**Comment by austinarbor** [comment]
This is incredible, I was working on a PR that looks almost identical to yours but I was still working on the codegen changes. Thanks for working on this so quickly, I will take a closer look no later than Monday EOD

**Comment by austinarbor** [comment]
I played around with the code locally and everything seems to be working perfectly for `jsonb` and `jsonb[]` types for both reading and writing values.

Was there anything specifically in the PR codewise you wanted me to look at?

```kotlin
class MapStringAnyType : JdbcUserDefinedDataType<Map<String, Any>> {
  override val type = typeOf<Map<String, Any>>()
  override val name = "jsonb"
  override val jdbcType = JDBCType.OTHER
  private val mapper = ObjectMapper()

  override fun getValue(
      rs: ResultSet,
      index: Int,
  ): Map<String, Any>? {
    val s = rs.getString(index) ?: return null
    return mapper.readValue(s)
  }

  override fun getValue(
      rs: ResultSet,
      columnLabel: String,
  ): Map<String, Any>? {
    return getValue(rs, rs.findColumn(columnLabel))
  }

  override fun setValue(
      ps: PreparedStatement,
      index: Int,
      value: Map<String, Any>,
  ) {
    ps.setObject(
        index,
        JsonMapperFactory.DEFAULT_MAPPER.writeValueAsString(value),
        Types.OTHER,
    )
  }

  override fun toString(value: Map<String, Any>): String {
    return value.toString()
  }
}

class ListMapStringAnyType : JdbcUserDefinedDataType<List<Map<String, Any>>> {
  override val name: String = "jsonb[]"
  override val jdbcType = JDBCType.ARRAY
  override val type = typeOf<List<Map<String, Any>>>()
  private val mapper = ObjectMapper()

  override fun getValue(
      rs: ResultSet,
      index: Int,
  ): List<Map<String, Any>>? {
    val array = rs.getArray(index)?.array as? Array<String> ?: return null
    return array.map { mapper.readValue<Map<String, Any>>(it) }
  }

  override fun getValue(
      rs: ResultSet,
      columnLabel: String,
  ): List<Map<String, Any>>? {
    val index = rs.findColumn(columnLabel)
    return getValue(rs, index)
  }

  override fun setValue(
      ps: PreparedStatement,
      index: Int,
      value: List<Map<String, Any>>,
  ) {
    val array: Array<String> =
        value.map { mapper.writeValueAsString(it) }.toTypedArray()
    ps.setArray(index, ps.connection.createArrayOf("jsonb", array))
  }

  override fun toString(value: List<Map<String, Any>>): String {
    return value.toString()
  }
}
```

**Comment by nakamura-to** [comment]
The release will be done by mid-August.

**Comment by austinarbor** [comment]
awesome, can't wait. appreciate it!

**Comment by nakamura-to** [comment]
We have expedited the release and launched v2.0.0. Please feel free to use it.
https://github.com/komapper/komapper/releases/tag/v2.0.0

**Comment by austinarbor** [comment]
Thank you! I will be migrating my codebase tomorrow

**Comment by brizzbuzz** [comment]
Is it possible to filter on keys within JSON data using this approach?

**Comment by nakamura-to** [comment]
@brizzbuzz It might be possible, but this approach may not be the most optimal. Could you provide a bit more detail about what you're trying to achieve? It might be better to explain it in a new issue or discussion.
