### ISSUE TITLE
OffsetDateTime Offset Coercion

### ISSUE THREAD

**Issue by austinarbor** [komapper/komapper#1308]
### Use case
I have a bunch of columns in my (postgres) database that are using `timestamp without timezone`. Due to the size of the database, it's unfortunately not feasible to migrate all of these columns to `timestamp with timezone`. In the database, these columns always store values in UTC.

In my entities, I want to always use `OffsetDateTime`. There are no errors or issues parsing the timestamp to an `OffsetDateTime`, however, when it does, it sets the offset to the offset of the current machine. Is there an easy way for me to force use the UTC offset instead of my local offset?

I'll admit this is a pretty low priority thing because it really only affects my local configuration - the deployed application has UTC set as the timezone so everything works as expected there.

### Describe the solution you'd like

A way to specify the offset/timezone to parse `timestamp without timezone` values in.

### Versions

- Komapper: 1.18.1
- Kotlin: 2.0.0
- JVM: 21
- JDBC Driver or R2DBC Driver: Both
- Database: Postgresql
- OS: OSX

**Comment by momosetkn** [comment]
You can set the time-zone using the following code.

```kotlin
import java.util.TimeZone

fun setTimeZone() {
    TimeZone.setDefault(TimeZone.getTimeZone("UTC"))
}
```

**Comment by nakamura-to** [comment]
Another approach is to use `DataTypeConverter`.
See https://www.komapper.org/docs/reference/data-type/#data-type-conversion.

For example, implement the wrap function with the following code:

```kotlin
class OffsetDateTimeTypeConverter : DataTypeConverter<OffsetDateTime, OffsetDateTime> {
    override val exteriorClass: KClass<OffsetDateTime> = OffsetDateTime::class
    override val interiorClass: KClass<OffsetDateTime> = OffsetDateTime::class

    override fun unwrap(exterior: OffsetDateTime): OffsetDateTime {
        return exterior
    }

    // This function is executed before returning the value retrieved from the database to the application.
    override fun wrap(interior: OffsetDateTime): OffsetDateTime {
        // Return the new OffsetDateTime value.
    }
}
```

**Comment by austinarbor** [comment]
@nakamura-to @momosetkn thank you both - these are both ideas I should have thought of already
