### ISSUE TITLE
KomapperAutoIncrement for mysql onDuplicateKeyUpdate not working

### ISSUE THREAD

**Issue by jungle817** [komapper/komapper#1311]
data class Address(
    val addressId: Int = 0,
    val street: String,
    val version: Int = 0,
)

@KomapperEntityDef(Address::class)
data class AddressDef(
    @KomapperId
    @KomapperAutoIncrement
    val addressId: Nothing,
    @KomapperVersion
    val version: Nothing,
)

QueryDsl.insert(Meta.address).onDuplicateKeyUpdate().executeAndGet(Address(id=1, street = "new street"))

always insert into db,don't update the id eq 1

**Comment by jungle817** [comment]
QueryDsl.create(Meta.address)

QueryDsl.insert(Meta.address).onDuplicateKeyUpdate().executeAndGet(Address(id=1, street = "new street"))

always insert into db,don't update the id eq 1

**Comment by nakamura-to** [comment]
The auto-incremented values will never be duplicated.
I recommend adding a column that serves as a unique key to that table.

**Comment by jungle817** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好,您的邮件我已收到，我会尽快给你回复，谢谢。

**Comment by jungle817** [comment]
OK， thanks

**Comment by jungle817** [comment]
I still have a question
![image](https://github.com/komapper/komapper/assets/35696147/53dd5ecb-7811-4d75-9fd9-18991adfe0ff)

if using the h2 database,  the code assertEquals(1, tokyo?.addressId) is right, but using mysql it's error。

**Comment by jungle817** [comment]
I printed the sql for h2:
merge into address as t using (select address_id, street, version from values (?, ?, ?) as x (address_id, street, version)) as excluded on t.address_id = excluded.address_id when not matched then insert (street, version) values (excluded.street, excluded.version) when matched then update set t.street = excluded.street, t.version = excluded.version

the mysql sql:
insert into address (street, version) values ('tokyo street', 0) as excluded on duplicate key update street = excluded.street, version = excluded.version


I thinked when using KomapperAutoIncrement in mysql,the primary key address_id not working in the sql,but when useing h2,address_id is working，why?

**Comment by nakamura-to** [comment]
Thanks for your feedback.

When using H2, we emulate the syntax of `INSERT .. ON DUPLICATE KEY UPDATE` with the `MERGE` statement. However, it appears that the behavior cannot be fully emulated when the comparison target is an auto-increment column.

The correct behavior is that of MySQL.

**Comment by jungle817** [comment]
thank you
