### ISSUE TITLE
QueryDsl Update With Include - KomapperUpdatedAt Not Included

### ISSUE THREAD

**Issue by austinarbor-wk** [komapper/komapper#1331]
Should fields in the entity marked with `@KomapperUpdatedAt` be automatically included when using `QueryDsl.update(table).include(..)`?

According to the [docs](https://www.komapper.org/docs/reference/query/querydsl/update/#include) it looks like `@KomapperVersion` is , but when testing it with `@KomapperUpdatedAt`, the updatedAt column is not included in the update query when using include.

### Versions

- Komapper: 2.0.0
- Kotlin: 2.0.0
- JVM: 21
- JDBC Driver or R2DBC Driver: JDBC
- Database: Postgresql
- OS: OSX

**Comment by nakamura-to** [comment]
Thank you for your feedback.
You're absolutely right. 
I have fixed it.

**Comment by nakamura-to** [comment]
We have fixed this issue in Komapper v2.1.0. Please give it a try.

**Comment by austinarbor-wk** [comment]
works great, thank you!
