### ISSUE TITLE
Update Single Returns Entity Even if It Does Not Exist

### ISSUE THREAD

**Issue by austinarbor** [komapper/komapper#1413]
### Describe the bug

Consider a table where you just have a single entity

| id | name |
|---|---|
|1|github|

If you run an update query, the return value could be slightly deceiving

```kotlin
val site = Website(id = 2, name = "something")
val result = db.runQuery { QueryDsl.update(Meta.website).single(site) }
```

### Expected behavior
I would expect `result` to be null because the update did not actually update any records

### Actual behavior
`result` is not null

### Steps to reproduce the problem
The only way I have found so far to detect this is to include `returning()`

```kotlin
db.runQuery {
        QueryDsl.update(table).single(e).returning()
      }
```

This works, but seems wasteful if you have a large-sized row. If you have calculated values (`@KomapperUpdatedAt, @KomapperVersion`) you'll want those values back. Is there a better way of detecting if the update didn't really do anything? 

### Versions

- Komapper: 3.1.0
- Kotlin: 2.0.21
- JVM: 21
- JDBC Driver or R2DBC Driver: JDBC
- Database: Postgresql
- OS: OSX

**Comment by nakamura-to** [comment]
Thank you for your feedback. 
In this case, it seems correct for `db.runQuery` to return `null`. 
We’ll consider making this change.

**Comment by austinarbor** [comment]
Alternatively, I would be ok with an exception like `RecordNotFoundException` being thrown if the update is essentially a no-op.

In order to maintain backwards compatibility, maybe could add a new option to `UpdateOptions` to throw on no update performed?

**Comment by nakamura-to** [comment]
Thank you for your suggestion. 
I've addressed it in #1421. 
Please feel free to share any feedback.

**Comment by austinarbor** [comment]
@nakamura-to i tested locally and this looks good! working as expected, thank you!

**Comment by nakamura-to** [comment]
Close by #1421
