### ISSUE TITLE
Usage of the new UUID class causes opt in required error

### ISSUE THREAD

**Issue by Laxystem** [komapper/komapper#1420]
### Describe the bug

```kotlin
e: ./server/build/generated/ksp/main/kotlin/quest/laxla/gimli/server/database/_Instance.kt:50:149 This declaration needs opt-in. Its usage must be marked with '@kotlin.uuid.ExperimentalUuidApi' or '@OptIn(kotlin.uuid.ExperimentalUuidApi::class
```

### Expected behavior

It not happening

### Actual behavior

It happening

### Steps to reproduce the problem

Use `kotlin.uuid.Uuid`, e.g.

```kotlin
@OptIn(ExperimentalUuidApi::class)
@KomapperEntity
data class Instance(
    @KomapperId
    val id: Uuid = databaseRandom.nextUuidV7(),
    val uri: Uri?, // TODO: unique
    @KomapperCreatedAt
    val firstEncountered: Instant? = null
)
```

### Versions

- Komapper: 3.1.0
- Kotlin: 2.0.20
- JVM: 21?
- JDBC Driver or R2DBC Driver: unknown
- Database: postgres 16
- OS: linux

**Comment by nakamura-to** [comment]
Komapper generates code at compile-time.
To make kotlin.uuid.Uuid available in the generated code, please specify the compile options in your build.gradle.kts:

```kotlin
tasks {
    withType<KotlinCompile>().configureEach {
        compilerOptions {
            freeCompilerArgs = listOf("-opt-in=kotlin.uuid.ExperimentalUuidApi")
        }
    }
}
```

At this point, Komapper does not support mapping between `kotlin.uuid.Uuid` and the database, so conversion code like the following is required:
```kotlin
class UuidTypeConverter : DataTypeConverter<Uuid, java.util.UUID> {
    override val exteriorType: KType = typeOf<Uuid>()
    override val interiorType: KType = typeOf<java.util.UUID>()

    override fun unwrap(exterior: Uuid): java.util.UUID {
        return exterior.toJavaUuid()
    }

    override fun wrap(interior: java.util.UUID): Uuid {
        return interior.toKotlinUuid()
    }
}
```

For more details, please refer to https://www.komapper.org/docs/reference/data-type/#data-type-conversion.
