### ISSUE TITLE
Improve navigation bar

### ISSUE THREAD

**Issue by rohitmore07** [komapper/komapper#1435]
Want to improve navigation bar UI with fab hover and animations.

**Comment by nakamura-to** [comment]
@rohitmore07 Could you provide more details? I'm wondering if perhaps you might have intended to post this elsewhere.

**Comment by nakamura-to** [comment]
Please create an issue regarding the [website](https://www.komapper.org/) in the following repository:  https://github.com/komapper/komapper-docs. If you would like to request a modification, it would be helpful to attach a screenshot along with a written description.

**Comment by nakamura-to** [comment]
Please create an issue regarding the [website](https://www.komapper.org/) in the following repository:  https://github.com/komapper/komapper-docs. If you would like to request a modification, it would be helpful to attach a screenshot along with a written description.

**Comment by rohitmore07** [comment]
Apologies for the confusion! I might have posted in the wrong place.
I’d like to improve the UI of Komapper's website navbar. 
Could you guide me to the correct place to raise an issue for improving the UI on Komapper's website navbar?

**Comment by rohitmore07** [comment]
> Please create an issue regarding the [website](https://www.komapper.org/) in the following repository: https://github.com/komapper/komapper-docs. If you would like to request a modification, it would be helpful to attach a screenshot along with a written description.

Done!
