### ISSUE TITLE
Kotlin 2.1.0 Compatibility issue

### ISSUE THREAD

**Issue by hantsy** [komapper/komapper#1462]
Failed to build when upgrading to Kotlin 2.1.0.

https://github.com/hantsy/spring-r2dbc-sample/actions/runs/12061917240/job/33634757623

**Comment by nakamura-to** [comment]
Thank you for the report. Could you show me the error message?

**Comment by nakamura-to** [comment]
Apologies. I was able to review the error message. This issue will be resolved in #1460.

**Comment by nakamura-to** [comment]
Please try Komapper v5.0.0.
https://github.com/komapper/komapper/releases/tag/v5.0.0

**Comment by hantsy** [comment]
Verified, works as always. Thanks for your quick fix.
