### ISSUE TITLE
[R2dbc] Insert Multiple should accept Flow as method params

### ISSUE THREAD

**Issue by hantsy** [komapper/komapper#1467]
### Use case

Currently the `QueryDsl.insert(entity).multiple()` only accepts `List` or varied array, it should accept Kotlin `Flow` and also can return a `Flow`.

R2dbc itself embraces Reactive Streams, and `Flow` is a good match with Reactive Streams.

### Versions

- Komapper: 5.0.0
- Kotlin: 2.1.0
- JVM: 21
- JDBC Driver or R2DBC Driver: R2dbc Postgres 
- Database: Postgres 
- OS: Windows 10 Pro

**Comment by GreyTeardrop** [comment]
5c from a perspective of fellow Komapper user:
1. It would be pretty cool to support `Flow` return types and be able to stream large data sets without loading all the set into memory. I can imagine that would be a rather involved and large-scale change.
2. I'm not really sure if accepting a `Flow` as input would make much sense. What semantics would one expect it to have? Wait for the `Flow` to complete and send a single insert command to the DB? Send insert commands one-by-one every time new item is emitted by the `Flow`? Former is probably better expressed by existing signature that accepts a list, latter can be simulated by doing `flow.map { record -> db.execute(QueryDsl.insert(metamodel).single(record) }` (and is probably less efficient that waiting for the whole flow and sending a single command).

**Comment by nakamura-to** [comment]
Thank you for the feedback.

Currently, with `R2dbcDatabase`, it is possible to receive query results as a `Flow`:

```kotlin
val db = R2dbcDatabase("r2dbc:h2:mem:///example;DB_CLOSE_DELAY=-1")
val a = Meta.address
val query: FlowQuery<Address> = QueryDsl.from(a)
val flow: Flow<Address> = db.flowQuery(query)
```
However, there is no feature for accepting parameters as a Flow.

I agree with GreyTeardrop on this matter—I do not believe there would be any significant benefit in implementing such functionality.

**Comment by hantsy** [comment]
> I'm not really sure if accepting a Flow as input would make much sense. What semantics would one expect it to have? Wait for the Flow to complete and send a single insert command to the DB? Send insert commands one-by-one every time new item is emitted by the Flow? Former is probably better expressed by existing signature that accepts a list, latter can be simulated by doing flow.map { record -> db.execute(QueryDsl.insert(metamodel).single(record) } (and is probably less efficient that waiting for the whole flow and sending a single command).

R2dbc supports batch, it is good to implement this with batch. For a `Flow` input, cache it till it archives the batch size and save it in batch.

**Comment by nakamura-to** [comment]
@hantsy  Thank you for sharing your thoughts.

Do you have a need to execute R2DBC batch operations using a Flow as input? Please note that the [PostgreSQL R2DBC Driver](https://github.com/pgjdbc/r2dbc-postgresql) does not support batch execution for statements with bind variables. As a result, even if Komapper were to implement batch execution using Flow as input, you might not be able to use it.

If your goal is simply to split a Flow and perform multiple inserts, you can achieve that with the following approach:

```kotlin
val a = Meta.address
val flow = flowOf(
    Address(16, "STREET 16", 0),
    Address(17, "STREET 17", 0),
    Address(18, "STREET 18", 0),
    Address(19, "STREET 19", 0),
    Address(20, "STREET 20", 0),
    Address(21, "STREET 21", 0),
    Address(22, "STREET 22", 0),
)
val list = flow.chunked(2).map {
    db.runQuery { QueryDsl.insert(a).multiple(it) }
}.toList()
```
