### ISSUE TITLE
Add dump scritps to QueryDsl

### ISSUE THREAD

**Issue by hantsy** [komapper/komapper#1468]
### Use case

Currently, we can drop and create db schema from metadata, please add fun to dump the portable scripts into output streams(`FileOutputStream`)/byte buffer(`Flux<DataBuffer>` in spring module), etc.

### Describe the solution you'd like

Provides an `options` to configure the content of dumping scripts,  
1. keywords uppercase or lowercase
2. if dump data?
3. etc.

### Versions

- Komapper: 5.0.0
- Kotlin: 2.1.0
- JVM: 21
- JDBC Driver or R2DBC Driver: both Jdbc Driver and R2DBC Driver
- Database: Postgres
- OS: Windows 10 Pro

**Comment by nakamura-to** [comment]
Thank you for the feedback.

Would [pg_dump](https://www.postgresql.org/docs/current/app-pgdump.html) be the best option for your request?

The `dryRunQuery` function might meet some of your needs:
```kotlin
val result: DryRunResult = db.dryRunQuery {
    QueryDsl.create(a)
}
println(result.sql)
```
