### ISSUE TITLE
Support for Apple M1 Chips

### ISSUE THREAD

**Issue by unredundant** [komapper/komapper#587]
### Describe the bug

Hey 👋 Neat project.  I'm particularly intrigued by the R2DBC support + the spring integration.  I haven't found anything yet that plays well with both.  Was very excited to give this a go, unfortunately it looks like currently M1 macs are not supported.

### Expected behavior

Support M1s :) 

### Actual behavior

When trying to run the r2dbc spring example with this command `./gradlew :spring-boot-r2dbc:bootRun` I get the following 

```
* What went wrong:
A problem occurred configuring project ':gradle-plugin'.
> Failed to calculate the value of task ':gradle-plugin:compileJava' property 'javaCompiler'.
   > Unable to download toolchain matching these requirements: {languageVersion=11, vendor=any, implementation=vendor-specific}
      > Unable to download toolchain. This might indicate that the combination (version, architecture, release/early access, ...) for the requested JDK is not available.
         > Could not read 'https://api.adoptopenjdk.net/v3/binary/latest/11/ga/mac/aarch64/jdk/hotspot/normal/adoptopenjdk' as it does not exist.
```

This stems from the fact that there very little ARM support for JDK 11.  To my knowledge, the only available vendor with ARM support is [Azul](https://www.azul.com/newsroom/azul-announces-support-of-java-builds-of-openjdk-for-apple-silicon/). 

It's interesting that gradle can't pick this up since you have `vendor=any`.  I would assume that they would cross reference the JDK compatability with the CPU architecture, but Gradle is weird 🤷 

### Steps to reproduce the problem

Buy a new computer 🤠 Just kidding... kinda? 

### Versions

- Komapper: latest (master branch) 
- Kotlin: 1.6.21
- JVM: 18 (though with toolchain, shouldn't matter right?)
- JDBC Driver or R2DBC Driver: whatever is in the example 
- Database: whatever is in the example
- OS: MacOS (latest... big sur?)

**Comment by unredundant** [comment]
Couple things

small notes the documentation is a bit out of date

1. the command looks like it should be `./gradlew :example-spring-boot-r2dbc:bootRun` instead of `./gradlew :spring-boot-r2dbc:bootRun`
3. The endpoint(s) looks like it needs to be `http://localhost:8080/declarative` or `http://localhost:8080/declarative` instead of just `http://localhost:8080`

Secondly, for what it's worth, I bumped the toolchain version up to 17 and it works like a charm 🎉 I believe you can have a toolchain version be higher than the compile target, so perhaps a viable solution here is to set the toolchain version to 17, and to peg the compile target to 11? 

Or just set everything to 17 since that is the latest LTS version of Java :) 

up to the maintainers on that choice

**Comment by nakamura-to** [comment]
Hello, thanks your report.

We will consider removing the toolchain version 11 for users of Apple M1 Chips.

> small notes the documentation is a bit out of date

Please note that the [documentation](https://www.komapper.org/docs/examples/) is for examples in the [komapper/komapper-examples](https://github.com/komapper/komapper-examples) repository, not for ones in the [komapper/komapper](https://github.com/komapper/komapper) repository.

**Comment by unredundant** [comment]
Ah, that's all perfect then, thanks!
