### ISSUE TITLE
Array in PostgreSQL

### ISSUE THREAD

**Issue by cyr62110** [komapper/komapper#595]
### Describe the bug

I am trying to store array in my entity classes. 
According to the [Dialect documentation](https://www.komapper.org/docs/reference/dialect/#postgresql---r2dbc), I should use a kotlin.Array in my entity data class.

However as soon as I add an Array in my entity data class, I have a ksp error:
```
[ksp] /.../Example.kt:10: The property type must not have any type parameters.
```

### Expected behavior

The array is stored in the database.

### Actual behavior

Ksp error when building the application:

```
[ksp] /.../Example.kt:10: The property type must not have any type parameters.
```

### Steps to reproduce the problem

Create a data class with an kotlin.Array in it:
```kotlin
@KomapperEntity
data class Example(
    @KomapperId val id: UUID,
    val array: Array<String>
)
```

### Versions

- Komapper: 1.0.0-RC1
- Kotlin: 1.6.21
- JVM: openjdk version "11.0.11"
- JDBC Driver or R2DBC Driver: r2dbc-postgresql 0.9.1.RELEASE
- Database: PostgreSQL 13.5
- OS: macOS

**Comment by nakamura-to** [comment]
Thank you for your report.
I will investigate.
