### ISSUE TITLE
Add the ability to override how enums are mapped to the database.

### ISSUE THREAD

**Issue by donard-commedagh** [komapper/komapper#611]
### Use case

I would like to able to map enums in Kotlin to integers in the database. The pre-existing databases that I am developing against (in SQL Server) have all the enum-like columns stored as integers often with a backing constraint table.

### Describe the solution you'd like

I would like to be able to provide a custom DataType converter to map the enums but it does not work. The `komapper-processor` is currently hard-coded to prioitise mapping enums to strings.

https://github.com/komapper/komapper/blob/fdf89c272c272fa5b56ee8e18e1afb326b5ae4ee/komapper-processor/src/main/kotlin/org/komapper/processor/EntityFactory.kt#L62

### Versions

- Komapper: 1.0.0-RC1
- Kotlin: 1.6.21
- JVM: JDK 14.0.1
- JDBC Driver or R2DBC Driver: com.microsoft.sqlserver:mssql-jdbc:10.2.0.jre11
- Database: SQL Server 2014
- OS: Windows 10

**Comment by nakamura-to** [comment]
Thank you for your request.

We will consider introducing the following classes:

```kotlin
annotation class KomapperEnum(val type: EnumType = EnumType.NAME)

enum class EnumType {
    NAME, ORDINAL
}
```

For example, suppose we have a Color enum class:

```kotlin
enum class Color {
    BLUE, RED, YELLOW
}
```

With above classes, we can define a Pencil entity class like this:

```kotlin
@KomapperEntity
data class Pencil(
    @KomapperId
    val id: Int,
    @KomapperEnum(EnumType.ORDINAL)
    val color: Color
)
```

In this case, Komapper would convert `Color.BLUE` to `0`, `Color.RED` to `1`, and `Color.YELLOW` to `2`. And, of course, vice versa.

Does this idea fulfill your request?

**Comment by donard-commedagh** [comment]
That sounds like it should work.

I'm being slightly selfish here because my current project has about ~30 enum like definitions in the database, but it would be nice if the default EnumType could be specified project wide, for example in build.gradle, however that may not be viable and also may cause confusion to people who aren't looking for it.

**Comment by nakamura-to** [comment]
> it would be nice if the default EnumType could be specified project wide, for example in build.gradle

Good idea! We might use a KSP argument to achieve it:

```kotlin
ksp {
    args("komapper.enumStrategy", "ordinal") // With this argument, EnumType.ORDINAL is used as the default
}
```

> may cause confusion to people who aren't looking for it

Yes, it is true. But we consider it acceptable.

**Comment by nakamura-to** [comment]
By the way, you can use value class instead of enum class.
For example, the following code works with Komapper 1.0.0-RC1:

```kotlin
@JvmInline
value class Color(val value: Int) {
    companion object {
        val BLUE = Color(0)
        val RED = Color(1)
        val YELLOW = Color(2)
    }
}

@KomapperEntity
data class Pencil(
    @KomapperId
    val id: Int,
    val color: Color
)
```

**Comment by donard-commedagh** [comment]
That's a good idea, I've only just read up on value classes in the last week and haven't used them anywhere yet. As a temporary fix, I can live without the exhaustive when(enum) and enum.values()

Thank you for the excellent work developing Komapper.
