### ISSUE TITLE
Generated code for Enums does not use fully qualified class names

### ISSUE THREAD

**Issue by donard-commedagh** [komapper/komapper#627]
### Describe the bug

The KSP generated code for the enums does not use a fully qualified name and will not compile the `entities` and `entityDefinitions` come from different packages.

### Expected behavior

The KSP generated code will compile.

### Actual behavior
The KSP generated code fails with:
```Unresolved reference: ExampleEnum```

Example generated lines for an enum and a value class:
```
val `exampleEnum` = org.komapper.core.dsl.metamodel.PropertyDescriptor<pkg.db.model.Table, pkg.db.enums.ExampleEnum, Int>(pkg.db.enums.ExampleEnum::class, Int::class, "exampleEnum", "ExampleEnum", false, false, { it.`exampleEnum }, { e, v -> e.copy(`exampleEnum` = v) },
    { ExampleEnum.values()[it] }, { it.ordinal }, true)
val `exampleValueClass` = org.komapper.core.dsl.metamodel.PropertyDescriptor<pkg.db.model.Table, pkg.db.enums.ExampleValueClass, kotlin.Int>(pkg.db.enums.ExampleValueClass::class, kotlin.Int::class, "exampleValueClass", "ExampleValueClass", false, false, { it.`exampleValueClass` }, { e, v -> e.copy(`exampleValueClass` = v) },
    { pkg.db.enums.ExampleValueClass(it) }, { it.value }, true)
```
__Note:__ I've obfuscated the above by hand so there may be typos, but the important bits are the start of lines 2 & 4.

### Steps to reproduce the problem

Create a project with the `entities.kt` and `entityDefinitions.kt` in different packages and use at least one enum.

### Versions

- Komapper: 1.1.1
- Kotlin: 1.6.21
- JVM: 14.0.1
- JDBC Driver or R2DBC Driver: Not applicable
- Database: Not applicable
- OS: Not applicable

**Comment by donard-commedagh** [comment]
Slight mistake in the explanation above:
When the `Enum` is in a different package to the `entities`, it won't compile.
In the example generated code above the `value class` is in a different package to the `entities` and works fine.

**Comment by nakamura-to** [comment]
Thanks for your report.
I will fix it.
