### ISSUE TITLE
why do u use R2DBC 

### ISSUE THREAD

**Issue by fizz12344321** [komapper/komapper#654]
Hi, i am reading your project and i am interested in this, but i have a question, why do you use R2DBC instead of other non blocking IO like Hibernate Reactive or others... can you tell me your purpose, the pros and cons of R2DBC, thank you so much

**Comment by nakamura-to** [comment]
Thanks for your interest in Komapper.
The purpose of Komapper is to provide almost same API for blocking and non-blocking database access.
R2DBC SPI(service-provider interface) is minimal and simple to wrap with Komapper API. But Hibernate Reactive API is not.
