### ISSUE TITLE
Number type bound in ArithmeticExpression

### ISSUE THREAD

**Issue by chipnesh** [komapper/komapper#675]
### Use case

I use a custom big decimal type and I faced a problem integrating it.
My custom big decimal doesn't extend "kotlin.Number" so I can't use it in the following expressions:
```
QueryDsl
    .update(a)
    .set { a.balance eq a.balance.plus(amount) }
    .where { a.userId eq a.userId }
```

### Describe the solution you'd like

I see that this Number type is not even used:
```
is ArithmeticExpression.Plus<*, *> -> {
                visitOperand(expression.left)
                buf.append(" + ")
                visitOperand(expression.right)
            }
```
Maybe it makes sense to get rid of it?

### Versions

- Komapper: 1.1.2
- Kotlin: 1.7.10
- JVM: 11
- JDBC Driver or R2DBC Driver: postgresql
- Database: postgresql
- OS: windows

**Comment by nakamura-to** [comment]
We want to allow the plus operation only on Number types.

By the way, why does not your custom big decimal extend `kotlin.Number`?
How about converting it to `kotlin.Number` before binding?
