### ISSUE TITLE
Trim String-based columns in data class

### ISSUE THREAD

**Issue by jhult** [komapper/komapper#692]
### Use case

In my database, some `VARCHAR` values have extra spaces at the end.

### Describe the solution you'd like

I would like an easy way to flag a `KomapperColumn` so that its value will be [trimmed](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/trim.html). Perhaps this could be an additional property (a `Boolean`) on `KomapperColumn` that defaults to `false`, but when `true`, would `trim` the column value.

### Possible issues

I suppose if we took the data class and tried to update the database with it, we would not necessarily want to use the trimmed value.

### Versions

- Komapper: 1.2.0
- Kotlin: 1.7.10
- JVM: OpenJDK Runtime Environment Zulu11.56+19-CA (build 11.0.15+10-LTS)
- JDBC Driver or R2DBC Driver: JDBC
- Database: Oracle
- OS: macOS 12.4

**Comment by nakamura-to** [comment]
I would like to propose a different solution.
How about using [data type conversion](https://www.komapper.org/docs/reference/data-type/#data-type-conversion)?
Here is an example code:

```kotlin
data class TrimmedString(val value: String): CharSequence by value {
    override fun toString(): String {
        return value
    }
}
```

```kotlin
class TrimmedStringTypeConverter: DataTypeConverter<TrimmedString, String> {
    override val exteriorClass: KClass<TrimmedString> = TrimmedString::class
    override val interiorClass: KClass<String> = String::class

    override fun unwrap(exterior: TrimmedString): String {
        return exterior.value
    }

    override fun wrap(interior: String): TrimmedString {
        return TrimmedString(interior.trim())  // Trim a String value when it is retrieved from database
    }
}
```

Register the above `TrimmedStringTypeConverter` in the `META-INF/services/org.komapper.core.spi.DataTypeConverter`.

You can define your entity class as follows:

```kotlin
@KomapperEntity
data class Employee(
    @KomapperId @KomapperAutoIncrement
    val id: Int = 0,
    val name: TrimmedString,
)
```

**Comment by jhult** [comment]
Thanks for the recommendation (and fast response). Since I wanted to catch inline classes, I decided to go this route to trim all Strings. Obviously there are some caveats to this approach, but I think it will work for my use case.

```
/**
 * Trim all `String` values that come from the Database before the value goes into a Kotlin class.
 * 
 * This works for both `String` classes and inline `String` classes.
 *
 * Note: If a value is subsequently updated back into the Database, it will change the Database value!
 */
class StringTypeConverter : DataTypeConverter<String, String> {
    override val exteriorClass: KClass<String> = String::class
    override val interiorClass: KClass<String> = String::class

    override fun unwrap(exterior: String): String {
        return exterior
    }

    override fun wrap(interior: String): String {
        return interior.trim()
    }
}
```

The above code is provided under [The Unlicense](https://opensource.org/licenses/Unlicense) and is thus free and unencumbered software released into the public domain.
