### ISSUE TITLE
Support MySQL5 for DELETE query.

### ISSUE THREAD

**Issue by naoki-tomita** [komapper/komapper#695]
### Use case

komapper generate query when execute the code.

```kotlin
db.runQuery { 
  QueryDsl.delete(someTable).where { someTable.id inList listOf(1, 2, 3) } 
}
// --> delete from some_table as t0_ where t0_.id in (?);
```

But, MySQL5 is not supported table alias.
MySQL throws `ERROR 1064 (42000)` .

### Describe the solution you'd like

komapper should generate query like belows if database is MySQL5.
(I don't know if it is possible...)

```SQL
delete aa from some_table as aa where aa.user_id in (?);
```

### Versions

- Komapper: 1.1.2
- Kotlin: 1.7.10
- JVM: 11
- JDBC Driver or R2DBC Driver: JDBC
- Database: MySQL5
- OS: Ubuntu 22

**Comment by nakamura-to** [comment]
Currently MySQL 5 is not supported.
However, you can avoid this problem by creating your own dialect:

```kotlin
val url = "jdbc:mysql://localhost/test"
val defaultDialect = JdbcDialects.get("mysql")
val customDialect = object : JdbcDialect by defaultDialect {
    override fun supportsAliasForDeleteStatement() = false
}

val db = JdbcDatabase(url, dialect = customDialect)
```

Now you can execute your query without any exceptions:

```kotlin
db.runQuery { 
  QueryDsl.delete(someTable).where { someTable.id inList listOf(1, 2, 3) } 
}
// --> delete from some_table where id in (?);
```

**Comment by naoki-tomita** [comment]
I was able to solve the problem by the method presented!

Thank you!!

**Comment by nakamura-to** [comment]
Just FYI, you can accomplish the same thing using the Service Provider Interface.
This approach makes `JdbcDatabase` instantiation simple.
Here is an example.

## Step 1

Create a `JdbcDialectFactory` implementation class: 

```kotlin
package example

import org.komapper.dialect.mysql.jdbc.MySqlJdbcDialect
import org.komapper.jdbc.JdbcDialect
import org.komapper.jdbc.spi.JdbcDialectFactory

class CustomDialectFactory : JdbcDialectFactory {

    private val mySqlDialect = MySqlJdbcDialect()

    override val priority: Int get() = super.priority + 10
    
    override fun supports(driver: String): Boolean {
        return driver.lowercase() == mySqlDialect.driver
    }

    override fun create(): JdbcDialect {
        return object : JdbcDialect by mySqlDialect {
            override fun supportsAliasForDeleteStatement(): Boolean = false
        }
    }
}
```

## Step 2

Register the above class in a file with the following name:

- `META-INF/services/org.komapper.jdbc.spi.JdbcDialectFactory`

## Step 3

Use the your own dialect in your application:

```kotlin
val url = "jdbc:mysql://localhost/test"
val db = JdbcDatabase(url) // this db instance uses your own dialect
```

You don't need to specify the dialect in the application. It is loaded implicitly.
