### ISSUE TITLE
Nullable columns are not nullable when compiled when using TypeAliases

### ISSUE THREAD

**Issue by Ayfri** [komapper/komapper#729]
### Describe the bug

Using this data class
```kt
typealias Snowflake = Long

@KomapperEntity
data class Test(
	@KomapperId @KomapperColumn("test_id") val id: Snowflake
	val optionalId: Snowflake?
)
```
If I try to select a row where `optionalId` is null, I get an error `null cannot be cast to non-null type kotlin.Long`
At a line that shows
```kt
`optionalId` = m[this.`optionalId`] as kotlin.Long, // should be `kotlin.Long?`
```

### Versions

- Komapper: 1.3.0
- Kotlin: 1.7.10
- JVM: OpenJDK 17.0.2
- JDBC Driver or R2DBC Driver: JDBC Driver
- Database: MySQL 8.0.25
- OS: Windows 11

**Comment by nakamura-to** [comment]
Thanks for your report!
This fix will be released in the next version.
