### ISSUE TITLE
R2DBC Postgres gradle build does not work out of the box

### ISSUE THREAD

**Issue by unredundant** [komapper/komapper#826]
### Describe the bug

Hey.  In order to get my gradle build to assemble correctly, I had to add the following dependency

```kotlin
implementation("org.postgresql:r2dbc-postgresql:1.0.0.RELEASE")
```

Perhaps [this](https://github.com/komapper/komapper/blob/c2ca8ac28381f480bca1c4a92827405b55f1c33a/komapper-dialect-postgresql-r2dbc/build.gradle.kts#L6) line is not able to correctly assign the proper dependency version?

My komapper dependencies in my gradle build are the following

```kotlin
platform("org.komapper:komapper-platform:$komapperVersion").let {
    implementation(it)
    ksp(it)
  }
  implementation("org.komapper:komapper-starter-r2dbc")
  implementation("org.komapper:komapper-dialect-postgresql-r2dbc")
  ksp("org.komapper:komapper-processor")
```

### Expected behavior

Gradle build should assemble properly without additional dependency

### Actual behavior

Gradle build fails

### Steps to reproduce the problem

Add the block I pasted above into a build file and try to assemble 

### Versions

- Komapper: 1.6.0
- Kotlin: 1.8.0
- JVM: 17
- JDBC Driver or R2DBC Driver: N/A
- Database: Postgres
- OS: Mac

**Comment by nakamura-to** [comment]
Hi. Thanks for your report.
The fix for this issue will be released in the next version.
