### ISSUE TITLE
Performance vs Exposed for simple CRUD

### ISSUE THREAD

**Issue by unredundant** [komapper/komapper#900]
### Describe the bug

Hi, this is not necessarily a bug, but just something that I've noticed running experiments vs other Kotlin ORMs.  I was just doing a simple load test on my local machine to a postgres instance running in docker.

Essentially, all I'm doing is spamming inserts for a specific table, and have noticed that Komapper is significantly slower than Exposed. 

Komapper result

<img width="846" alt="CleanShot 2023-02-18 at 14 16 33@2x" src="https://user-images.githubusercontent.com/5607577/219884316-d39c82e7-c095-4b4d-a16b-5a791f7679c0.png">

Exposed

<img width="744" alt="CleanShot 2023-02-18 at 14 19 07@2x" src="https://user-images.githubusercontent.com/5607577/219884330-9a8a3e45-584e-4bd5-9215-dbb70b290fee.png">

As you can see, the `http_req_duration` is nearly 5x higher for komapper vs exposed.  Curious if you guys have any idea why this may be (using JDBC for both, same repo, simply swapped out the persistence layer).  

Here is the K6 test if curious. 

```js
import http from 'k6/http';

export const options = {
    stages: [
        { target: 100, duration: '10s' },
        { target: 500, duration: '10s' },
        { target: 1000, duration: '10s' },
        { target: 500, duration: '10s' },
        { target: 100, duration: '10s' },
    ],
    thresholds: {
        http_req_failed: ['rate<0.001'],
        http_req_duration: ['p(95)<100'],
    },
};

export default function () {
    const url = 'http://localhost:8080/author';
    const payload = JSON.stringify({
        name: 'name',
    });

    const params = {
        headers: {
            'Content-Type': 'application/json',
        },
    };

    http.post(url, payload, params);
}
```

Just does a simple ramp up to 1000 virtual users over 10 second stages.

**Comment by nakamura-to** [comment]
Thanks for your post. 
Can you share your test code (including the persistence layer)? 
I want to investigate why Komapper is slower than Exposed.

**Comment by unredundant** [comment]
sure thing, here ya go https://github.com/unredundant/exposed-komapper-comp

Let me know if you have any problems running it, instructions are in the readme. 

I'm wondering if it could be that for Komapper I am not using a connection pool? I poked around in the `JdbcDatabase` but did not see a way to inject a connection pool the way you can using Exposed + Hikari.

**Comment by nakamura-to** [comment]
Thanks for sharing.

> I'm wondering if it could be that for Komapper I am not using a connection pool? I poked around in the JdbcDatabase but did not see a way to inject a connection pool the way you can using Exposed + Hikari.

You can rewrite [ConnectionManager.komapperDatabase](https://github.com/unredundant/exposed-komapper-comp/blob/49f1aa3449c8e820497a6795f393b1cb6caa0554/persistence/src/main/kotlin/io/bkbn/sourdough/persistence/ConnectionManager.kt#L26-L28) as follows:

```kotlin
    val komapperDatabase: JdbcDatabase by lazy {
        val dataSource = HikariDataSource(HikariConfig().apply {
            jdbcUrl = PostgresConfig.CONNECTION_URI
            username = PostgresConfig.USER
            password = PostgresConfig.PASSWORD
            maximumPoolSize = PostgresConfig.DEFAULT_MAX_POOL_SIZE
            initializationFailTimeout = PostgresConfig.DEFAULT_INIT_FAIL_TIMEOUT
            isAutoCommit = false
            transactionIsolation = "TRANSACTION_REPEATABLE_READ"
            validate()
        })
        JdbcDatabase(dataSource = dataSource, dialect = PostgreSqlJdbcDialect())
    }
```

Could you rerun the performance test with this configuration?

**Comment by unredundant** [comment]
yep, that was it, thanks! komapper is actually 35% faster when the connection pool is properly configured
