### ISSUE TITLE
Support of ON CONFLICT DO NOTHING;

### ISSUE THREAD

**Issue by Distractic** [komapper/komapper#929]
### Use case

Do nothing  when you try to insert  with an existing primary key

### Describe the solution you'd like

Add DSL to support  the SQL instruction `ON CONFLICT DO NOTHING;` [Doc in PSQL](https://www.postgresql.org/docs/current/sql-insert.html)

### Versions

- Komapper: 1.8.0
- Kotlin: 1.8.0
- JVM: 17
- JDBC Driver or R2DBC Driver: R2DBC 
- Database: PSQL

**Comment by nakamura-to** [comment]
It is already supported.
https://www.komapper.org/docs/reference/query/querydsl/insert/#onduplicatekeyignore

**Comment by Distractic** [comment]
Currently, this is my table  definitions : 

```sql
CREATE TABLE guild
(
    id         SERIAL                   NOT NULL,
    name       VARCHAR(50)              NOT NULL,
    owner      UUID                     NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE guild_member
(
    guild_id   INTEGER                  NOT NULL,
    member_id  UUID                     NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (guild_id, member_id),
    FOREIGN KEY (guild_id) REFERENCES guild (id) ON DELETE CASCADE ON UPDATE CASCADE
);
```

```kotlin
@KomapperEntity
@KomapperTable("guild")
@KomapperOneToMany(GuildMemberDef::class, "members")
public data class Guild(
    @KomapperId
    @KomapperAutoIncrement
    val id: Int,
    val name: String,
    val owner: UUID,
    @KomapperCreatedAt
    val createdAt: Instant,
)

public data class GuildMemberIds(
    public val guildId: Int,
    public val memberId: UUID,
)

@KomapperEntity
@KomapperTable("guild_member")
@KomapperManyToOne(Guild::class, "guild")
public data class GuildMemberDef(
    @KomapperEmbeddedId
    val id: GuildMemberIds,
    @KomapperCreatedAt
    val createdAt: Instant,
)
```

In my kotlin code, I want to return `false` if the user tries to insert a member with non existing guild.
For the moment, I have this exception: `insert or update on table "guild_member" violates foreign key constraint "guild_member_guild_id_fkey"`

I tried the following request : 
```kt
val result = QueryDsl.insert(memberMeta)
            .onDuplicateKeyIgnore()
            .executeAndGet(GuildMemberDef(GuildMemberIds(1, UUID.fromString("1e54c231-d511-4a78-8132-81c97730ffa2"), Instant.EPOCH))
```

or

```sql
INSERT INTO guild_member
VALUES (1, '1e54c231-d511-4a78-8132-81c97730ffa2', NOW())
ON CONFLICT DO NOTHING;
```

but both throw the exception.

The only workaround found is : 
```sql
INSERT INTO guild_member
                SELECT g.id, '1e54c231-d511-4a78-8132-81c97730ffa2', NOW()
                FROM guild g
                WHERE g.id = 1
```

I asked for help to build a better request in PSQL discord, but if there is no other solution, how can I do build a SQL similar request using the DSL?

Have a good day

**Comment by nakamura-to** [comment]
It would be good to first make sure that the data exists in the guild table.
For example, you could write:
```kotlin
val g = Meta.guild
val m = Meta.guildMemberDef

val query1 = QueryDsl.from(g).where { g.id eq 1 }.forUpdate().firstOrNull()
val query2 = QueryDsl.insert(m)
            .onDuplicateKeyIgnore()
            .executeAndGet(GuildMemberDef(GuildMemberIds(1, UUID.fromString("1e54c231-d511-4a78-8132-81c97730ffa2"), Instant.EPOCH))

val quild = db.runQuery(query1)
if (guild != null) {
    val member = db.runQuery(query2)
}
```

**Comment by Distractic** [comment]
I would like to avoid doing a double request for performance. This is possible with one request, so I would like to do this with the minimal of request

**Comment by nakamura-to** [comment]
The best solution may be to use the [executeTemplate](https://www.komapper.org/docs/reference/query/querydsl/template/#executetemplate
) function:

```kotlin
val sql = """
        INSERT INTO guild_member
        SELECT g.id, /*uuid*/'dummy-uuid', NOW()
        FROM guild g
        WHERE g.id = /*id*/0
    """.trimIndent()
val count = db.runQuery {
    QueryDsl.executeTemplate(sql)
        .bind("uuid", UUID.fromString("1e54c231-d511-4a78-8132-81c97730ffa2"))
        .bind("id", 1)
}
```

**Comment by Distractic** [comment]
`'dummy-uuid'` ? why not just `''`. Is there a difference between both ?

**Comment by nakamura-to** [comment]
No difference. Set any value you like. It is not actually used.
