### ISSUE TITLE
Define length of String column for creation table

### ISSUE THREAD

**Issue by Distractic** [komapper/komapper#932]
### Use case

Limited the length of  a varchar in database. (Currently, the length is 500 by default)

### Describe the solution you'd like

With  an annotation, for example, `@KomapperVarchar(length=25)`, we will be able to set the length constraint when a table is created

I don't know if you should verify the length of an inserted string before committing to the database. Need to discuss that maybe

### Versions

- Komapper: 1.8.0
- Kotlin: 1.8.0
- JVM: 17
- JDBC Driver or R2DBC Driver: R2DBC 
- Database: PSQL

**Comment by nakamura-to** [comment]
[SCHEMA Queries](https://www.komapper.org/docs/reference/query/querydsl/schema/)  are intended to be used for development purposes only. Therefore, detailed customization is not supported. I would like you to issue another CREATE TABLE and ALTER TABLE commands.

**Comment by Distractic** [comment]
I understand! So now I'm using a SQL file to init my database
