### ISSUE TITLE
Association API by entity ID

### ISSUE THREAD

**Issue by FeldrinH** [komapper/komapper#936]
### Use case

I generally use EntityStore with only *byId methods, because using the entire entity as key is expensive when I have large fields and breaks if I ever need to use a modified version of an entity in a lookup.

It would be nice to use the associations API, but as far as I can tell associations API helper methods always use the mapping methods that take the entire entity as key.

### Describe the solution you'd like

I would like to be able to enable a mode for the associations API where the generated methods use the *byId methods on the EntityStore.

### Versions

- Komapper: v1.8
- Kotlin: N/A
- JVM: N/A
- JDBC Driver or R2DBC Driver: N/A
- Database: N/A
- OS: N/A

**Comment by nakamura-to** [comment]
Hi, 

Thanks for the feedback.
I fixed it in #937.
If you have any comments on the fix, please let me know.
