### ISSUE TITLE
Call view and target komapper entity

### ISSUE THREAD

**Issue by Distractic** [komapper/komapper#946]
### Use case

Sometimes, we want to create a view with the same structure as a Komapper Entity.
However, instead of creating another Komapper Entity to interact with the view, it will be nice to give the name of the targeting view and return a Komapper Entity

### Describe the solution you'd like

Something  like : 

```kt
@KomapperEntity
@KomapperTable("guild_member")
@Serializable
public data class GuildMember(
    @KomapperId
    val guildId: Int,
    @KomapperId
    val entityId: String,
    @KomapperCreatedAt
    @Serializable(with = InstantSerializer::class)
    val createdAt: Instant = Instant.EPOCH,
)
```

```kt
fun getMembers(guildId: Int): Flow<GuildMember> {
    val meta = _GuildMember.guildMember

    val query = QueryDsl.from("guild_members_with_owner", meta).where {
        meta.guildId eq guildId
    }

    return database.flowQuery(query).filterNotNull()
}
```

The structure of `guild_members_with_owner` must match the structure of the Komapper  entity

### Versions

- Komapper: 1.8
- Kotlin: 1.8.10
- JVM: 17
- JDBC Driver or R2DBC Driver: R2DBC 
- Database: Postgres

**Comment by nakamura-to** [comment]
You can use the [clone](https://www.komapper.org/docs/reference/entity-class/#metamodel-clone) function.
Try the following code:

```kotlin
fun getMembers(guildId: Int): Flow<GuildMember> {
    val meta = _GuildMember.guildMember.clone(table = "guild_members_with_owner")

    val query = QueryDsl.from(meta).where {
        meta.guildId eq guildId
    }

    return database.flowQuery(query).filterNotNull()
}
```
