### ISSUE TITLE
Support for COALESCE operator

### ISSUE THREAD

**Issue by raharrison** [komapper/komapper#958]
### Use case

Support for the standard SQL coalesce operator within `SELECT` and `UPDATE` queries.

For simplest possible case in a select query:

```sql
SELECT COALESCE(p.address, 'default') FROM person p;
```

But for me currently, the more useful scenario is during updates to prevent having to retrieve the record first and performing a null-check on the column e.g.

```sql
UPDATE person p SET p.address = COALESCE(p.address, 'default') WHERE ...
```

### Describe the solution you'd like

Could potentially be added in much the same way as the existing operators within query expressions. The complexity might be due the fact that the operator would need to accept both literals or column references depending on the use.

```kotlin
QueryDsl.from(p)
    .select(p.id, coalesce(p.address, "default"))
```

and for updates:

```kotlin
QueryDsl.update(p).set {
  p.address eq coalesce(p.address, "default")
}
```

The sql operator itself accepts any number of parameters and picks the first non-null value, so perhaps an array or varargs option for those who need more flexibility?

### Versions

- Komapper: 1.9.0
- Kotlin: 1.8.20
- JVM: 17
- JDBC Driver or R2DBC Driver: JDBC
- Database: Postgres
- OS: N/A

**Comment by nakamura-to** [comment]
Thank you for the feedback!
It will be supported by #959.
If you have any comments, please let me know.
