### ISSUE TITLE
LocalDate Oracle - select works in 1.8; broken in 1.9

### ISSUE THREAD

**Issue by jhult** [komapper/komapper#964]
### Describe the bug

Running a query comparing a date (where `date` is a `LocalDate`) using the following worked in 1.8 but broke in 1.9:

```
val w2: WhereDeclaration = {
    obj.date.isNull()
    or { obj.date eq LocalDate.of(1700, 1, 1) }
    or { obj.date eq LocalDate.of(1900, 1, 1) }
}
```

### Cause

It looks like the [upgraded Oracle JDBC driver](https://github.com/komapper/komapper/pull/953) (21.9.0.0 -> 23.2.0.0) may have caused the issue. If I exclude `ojdbc11` from `komapper-dialect-oracle-jdbc` and then manually add the previous version (`ojdbc11:21.9.0.0`), it seems to work.

```
implementation("org.komapper:komapper-dialect-oracle-jdbc:1.9.0") {
    exclude("com.oracle.database.jdbc", "ojdbc11")
}
implementation("com.oracle.database.jdbc:ojdbc11:21.9.0.0")
```

### Versions

- Komapper: 1.9
- Kotlin: 1.8.20
- JVM: 11 (Amazon Coretto or Azul Zulu)
- JDBC Driver or R2DBC Driver: JDBC
- Database: Oracle
- OS: macOS or Linux

**Comment by nakamura-to** [comment]
I can not reproduce it.
What kind of error are you getting?
Can you show me the stack trace?

**Comment by jhult** [comment]
The query fails to return results. I'm not sure if an exception is thrown. Let me try to see if I can get you a stack trace.

**Comment by nakamura-to** [comment]
I could reproduce it.
This problem seems to be an issue with the Oracle JDBC Driver.
There seems to be a problem with the LocalDate binding.

```kotlin
val connection: java.sql.Connection = ...
val sql = """select id, "value" from local_date_data where "value" = ?"""
connection.prepareStatement(sql).use { ps ->
    ps.setObject(1, LocalDate.of(1700, 1, 1))
    val result = ps.executeQuery().use {rs ->
        if (rs.next()) {
            val id = rs.getInt(1)
            val date = rs.getObject(2, LocalDate::class.java)
            id to date
        } else {
            null to null
        }
    }
    println("result=$result")
}
```

In Oracle JDBC Driver 23.2.0.0, the above code outputs the following string:
```
result=(null, null)
```

However, in Oracle JDBC Driver 21.9.0.0, it outputs the following string:
```
result=(1, 1700-01-01)
```

**Comment by jhult** [comment]
@nakamura-to, should a patch for Kommaper be released that rolls back the Oracle driver update?

**Comment by nakamura-to** [comment]
Yes, I think so. I will rolls back the Oracle driver update next release.
Thanks for your report.
