### ISSUE TITLE
Code syntax for schema definition and mapping instead of annotations

### ISSUE THREAD

**Issue by Ombrelin** [komapper/komapper#972]
### Use case

To avoid having entities depending on the ORM framework, it would be nice to be able to define entity schema mapping in code.

### Describe the solution you'd like

The approach used in .NET's Entity Framework, called fluent syntax, is a very satisfying solution to this problem : https://learn.microsoft.com/en-us/ef/ef6/modeling/code-first/fluent/types-and-properties

**Comment by nakamura-to** [comment]
> To avoid having entities depending on the ORM framework,

In that case, you can use [separation mapping](https://www.komapper.org/docs/reference/entity-class/#separation-mapping-definition). Your entity classes does not need to have any annotations.

Does this solution meet your requirements?

**Comment by Ombrelin** [comment]
Thank you for your answer ! Yes it seems this feature covers my use case now that you point it out. It didn't quite understand it when I first came across it in the docs.
Thanks for the great tool !!
