### ISSUE TITLE
Extensions for native sql / custom operators in QueryDsl

### ISSUE THREAD

**Issue by raharrison** [komapper/komapper#986]
### Use case

Constructing and executing SQL using native features of a particular dbms provider. Ideally through Komapper QueryDsl so that you can still make use of all the mapping, predicate building, joins etc. For many additional scenarios this would avoid having to construct raw sql yourself unless it is explicitly needed.

For example a use case which utilises the full-text search capabilities of Postgres. This involves the use of a couple Postgres specific functions/operators which I think demonstrates the scenario quite well. Sample query:

```sql
SELECT id FROM books, phraseto_tsquery('english', 'search terms') query_ts
WHERE books.ts_doc @@ query_ts
--- AND....  --- could have many other predicates, joins here as need
ORDER BY ts_rank(ts_doc, query_ts) DESC;
```

This requires the the use of:
- additional entity through custom/native Postgres `phraseto_tsquery` function
- use of Postgres specific `@@` operator in where clause predicate
- order by with custom function `ts_rank`

The whole rest of the query (joins, additional predicates) can be constructed through standard Komapper QueryDsl features as usual.

The same thing would also be useful when dealing with JSON functionality within Postgres for example (without having to resort to manually created raw SQL).

### Describe the solution you'd like

I'm not sure if this is a good idea, but perhaps some way of adding custom SQL to QueryDsl to allow the use of such native syntax? That way you could still benefit from using Komapper to generate the bulk of the query for you, but fall-back to snippets of raw sql if you really need to for certain scenarios. The main benefit is staying in the QueryDsl world and not having to write the full query manually if only a very small custom portion is needed.

Or perhaps a way of creating your own custom Komapper operators/functions? Not sure if the API is built with that in mind or if this is possible? For example, this would be a simple way of adding in the `@@` operator on project specific basis without having to support it in the main tool. Custom user-defined functions etc could also be created to cover the other cases above as needed.

### Versions

- Kotlin: 1.8.21
- JVM: 17
- JDBC Driver or R2DBC Driver: both
- Database: Postgres
- OS: n/a

**Comment by nakamura-to** [comment]
Hi, thanks for your feedback.

We believe that it is better for Komapper to have built-in support for DBMS proprietary functions and operators than to allow users to add their own functions and operators.

Would you like support for the following functions and operators? Please let us know and we will implement them in Komapper:

- phraseto_tsquery function
- ts_rank function
- @@ operator

**Comment by raharrison** [comment]
That would be great for my use case, but I think up to you on how far you want to go into supporting specific DBMS functionality. 

In this scenario for example there are many Postgres specific `tsquery` related functions like `to_tsquery`, `plainto_tsquery`, `phraseto_tsquery`, `websearch_to_tsquery` that could be supported (https://www.postgresql.org/docs/current/textsearch-controls.html) and of course alternative functions for other databases.

I guess if added it would be as an addition to the Postgres specific dialect and then others could be added on a case-by-case basis if/when needed or requested. Trying to support all proprietary sql syntax and functions would be a very large undertaking I think.

**Comment by nakamura-to** [comment]
Yes, you are right.
We do not plan to support all syntaxes and functions. Instead, we plan to focus our support on those that users have the greatest need for.

**Comment by nakamura-to** [comment]
@raharrison Hi, we supported custom operators in Komapper v1.14.0.

Related pull requests are #1097, #1098, and #1099.

Documentation is here:
https://www.komapper.org/docs/reference/query/querydsl/expression/#user-defined-expression

This issue is closed, but feel free to comment if you have any suggestions.
